export const Users = [
  {
    id: 1,
    profilePicture: "ppic1.jpg",
    username: "Isabelle ",
  },
  {
    id: 2,
    profilePicture: "ppic2.jpg",
    username: "Jane Taylor",
  },
  {
    id: 3,
    profilePicture: "ppic3.jpg",
    username: "Meenakshi",
  },
  {
    id: 4,
    profilePicture: "ppic4.jpg",
    username: "Smita Singh",
  },
  {
    id: 5,
    profilePicture: "ppic5.jpg",
    username: "Sakshi",
  },
];

export const Posts = [
  {
    id: 1,
    description: "How's the shot :),Got my new lenses for my Canon.",
    photo: "post1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    description: "Its been an amazing month in Jaipur !Time for Gujrat",
    date: "15 mins ago",
    photo: "post2.jpg",

    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    description: "Have been experimenting with new cream textures!!",
    photo: "post3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    description: "Happy Diwali! buddies ,until next time",
    photo: "post4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    description: "Life achievment unlocked!!!Finally witnessed Northern Lights",
    photo: "post5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    description: "Sometimes taking a walk in the park is worth it ",
    photo: "post6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    description: "A cheat meal once in a while has to be paneer",
    photo: "post7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post8.jpg",
    description: "Happy holi friends!!leave a heart for papa!",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    description: "My obsession with just keeps on growing",
    photo: "post9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    description:
      "May your life be always filled with light, love, happiness and good health. Eid al-Adha Mubarak. ",
    photo: "post10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
